# Generated by Django 4.2.6 on 2023-10-18 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pw", models.CharField(max_length=25)),
                ("f_name", models.CharField(max_length=25)),
                ("l_name", models.CharField(blank=True, max_length=25)),
                ("phone", models.CharField(blank=True, max_length=11)),
                ("dob", models.DateField()),
                ("height", models.CharField(blank=True, max_length=3)),
                ("weight", models.CharField(blank=True, max_length=3)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
